
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN ELSE IF INT LBRACE LPAREN NEQ PLUS RBRACE RPAREN SEMI VAR WHILEprogram : stmtprogram : program SEMI stmtprogram : program SEMIstmt : VAR ASSIGN VAR PLUS INTstmt : VAR ASSIGN INT PLUS INTstmt : WHILE LPAREN VAR NEQ INT RPAREN LBRACE program RBRACEstmt : IF LPAREN VAR NEQ INT RPAREN LBRACE program RBRACEstmt : IF LPAREN VAR NEQ INT RPAREN LBRACE program RBRACE ELSE LBRACE program RBRACE'
    
_lr_action_items = {'VAR':([0,6,7,8,9,25,26,32,],[3,3,11,13,14,3,3,3,]),'WHILE':([0,6,25,26,32,],[4,4,4,4,4,]),'IF':([0,6,25,26,32,],[5,5,5,5,5,]),'$end':([1,2,6,10,19,20,29,30,34,],[0,-1,-3,-2,-4,-5,-6,-7,-8,]),'SEMI':([1,2,6,10,19,20,27,28,29,30,33,34,],[6,-1,-3,-2,-4,-5,6,6,-6,-7,6,-8,]),'RBRACE':([2,6,10,19,20,27,28,29,30,33,34,],[-1,-3,-2,-4,-5,29,30,-6,-7,34,-8,]),'ASSIGN':([3,],[7,]),'LPAREN':([4,5,],[8,9,]),'INT':([7,15,16,17,18,],[12,19,20,21,22,]),'PLUS':([11,12,],[15,16,]),'NEQ':([13,14,],[17,18,]),'RPAREN':([21,22,],[23,24,]),'LBRACE':([23,24,31,],[25,26,32,]),'ELSE':([30,],[31,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,25,26,32,],[1,27,28,33,]),'stmt':([0,6,25,26,32,],[2,10,2,2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> stmt','program',1,'p_program_single','while_parser.py',85),
  ('program -> program SEMI stmt','program',3,'p_program_seq','while_parser.py',89),
  ('program -> program SEMI','program',2,'p_program_trailing','while_parser.py',94),
  ('stmt -> VAR ASSIGN VAR PLUS INT','stmt',5,'p_stmt_assign','while_parser.py',98),
  ('stmt -> VAR ASSIGN INT PLUS INT','stmt',5,'p_stmt_assign_const','while_parser.py',106),
  ('stmt -> WHILE LPAREN VAR NEQ INT RPAREN LBRACE program RBRACE','stmt',9,'p_stmt_while','while_parser.py',114),
  ('stmt -> IF LPAREN VAR NEQ INT RPAREN LBRACE program RBRACE','stmt',9,'p_stmt_if','while_parser.py',119),
  ('stmt -> IF LPAREN VAR NEQ INT RPAREN LBRACE program RBRACE ELSE LBRACE program RBRACE','stmt',13,'p_stmt_ifelse','while_parser.py',124),
]
